# Generated by Django 5.0 on 2023-12-20 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cselect_app', '0003_remove_cartitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='CartItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cselect_app.cartitem'),
        ),
    ]
