# Generated by Django 5.0 on 2023-12-20 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cselect_app', '0004_orderdetail_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='CartItem',
            new_name='Cart_item',
        ),
    ]
