# Generated by Django 5.0 on 2023-12-20 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cselect_app', '0005_rename_cartitem_orderdetail_cart_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='Cart_item',
            new_name='cart_item',
        ),
    ]
